# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed559cd0ba0bc64fd42fb2fbad0486050c5a2285c1959272d02651ee1a514c71dd1ff8586fa2740aa9f0ae0e9902ab31f1bb782b3091a8c04f01537eedc24d1a

test:
  secret_key_base: 231daf7fef1db7988b0db39aa3c1fe7218fa4ca280b217be097be03ac26f17641919ce630ec729cff05ac19fcbeb6a23a096779d69aba7f2e5163c81dc5ec18d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
